name: "Build & Push Npm"
description: "Runs dockerfile to output version"
inputs:
  working_directory:
    description: "Working directory containing project"
    required: true
  github_token:
    description: "Github token to push nuget package"
    required: true
  next_version:
    description: "Next version"
    required: true
runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.8
    - name: Build Dockerfile
      run: |
        docker build -f ${{ inputs.working_directory }}/Dockerfile . --build-arg VERSION=${{ inputs.next_version }} -t core-grpc-npm-proto:${{ inputs.next_version }}
      shell: bash
    - name: Run Dockerfile & Push
      run: |
        docker run --rm -e NPM_TOKEN=${{ inputs.github_token }} --name npm-package core-grpc-npm-proto:${{ inputs.next_version }}
      shell: bash