name: "Build & Push Npm"
description: "Runs dockerfile to output version"
inputs:
  working_directory:
    description: "Working directory containing project"
    required: true
  github_token:
    description: "Github token to push nuget package"
    required: true
  next_version:
    description: "Next version"
    required: true
runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - run: npm --version
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - run: npm ci
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - run: npm run build
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - run: npm version ${{ inputs.next_version }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - run: mkdir -p ./bin
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - run: npm run pack
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - run: npm publish ./bin/core-grpc-web-protos-${{ inputs.next_version }}.tgz
      env:
        NPM_TOKEN: ${{ inputs.github_token }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash