name: "Build & Push Nuget"
description: "Runs dockerfile to output version"
inputs:
  working_directory:
    description: "Working directory containing project"
    required: true
  github_token:
    description: "Github token to push nuget package"
    required: true
  next_version:
    description: "Next version"
    required: true
runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v3
      shell: bash
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.x
    - name: Update nuget source
      working-directory: working_directory
      run: |
        echo $(pwd)
        echo $(ls -la)
        dotnet nuget update source github \
        --username "devan88" \
        --password ${{ inputs.github_token }} \
        --store-password-in-clear-text
      shell: bash
    - name: Restore dependencies
      working-directory: working_directory
      run: dotnet restore
      shell: bash
    - name: Build
      working-directory: working_directory
      run: dotnet build --no-restore --configuration ${{ env.configuration }}
      shell: bash
    - name: Pack
      working-directory: working_directory
      run: dotnet pack --configuration ${{ env.configuration }} -p:Version=${{ inputs.next_version }}
      shell: bash
    - name: Push
      working-directory: working_directory
      run: dotnet nuget push "**/bin/${{ env.configuration }}/*.nupkg" --source github
      shell: bash