name: "Get Semantic Version"
description: "Runs dockerfile to output version"
inputs:
  current_version:
    description: "Current version"
    required: true
  current_branch:
    description: "Current branch"
    required: true
  current_commit:
    description: "Current commit head"
    required: true
outputs:
  next_version:
    description: "The semantic version"
    value: ${{ steps.run-git-semver.outputs.next_version }}
runs:
  using: composite
  steps:
    - name: Run git-semver
      id: run-git-semver
      run: |
        docker pull ghcr.io/devan88/core-tools-git-semver:1.0.0
        next_version=$(docker run --rm ghcr.io/devan88/core-tools-git-semver:1.0.0 git-semver ${{ inputs.current_version }} ${{ inputs.current_branch }} ${{ inputs.current_commit }})
        echo "::set-output name=next_version::$(echo $next_version)"
      shell: bash