name: package-protos
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release"
      - "development"
jobs:
  build:
    defaults:
      run:
        working-directory: src/csharp/Core.Grpc.Protos
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x
      - name: Add nuget source
        run: >- 
          dotnet nuget add source "https://nuget.pkg.github.com/devan88/index.json" 
          --name "github" 
          --username "devan88"
          --password ${{ secrets.PUSH_PACKAGE }}
          --store-password-in-clear-text
        working-directory: /
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Pack
        run: dotnet pack --configuration Release
      - name: Push
        run: dotnet nuget push "**/bin/Release/*.nupkg" --source github