name: package-protos
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release"
      - "development"
      - "feature/*"
env:
  CONFIGURATION: "Release"
jobs:
  prepare-build:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.get-next-version.outputs.next_version }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set Env
        shell: bash
        run: |
          echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "CURRENT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Get Next Version
        id: get-next-version
        uses: ./.github/actions/get-semver
        with:
          current_version: "0.0.0"
          current_branch: ${{ env.CURRENT_BRANCH }}
          current_commit: ${{ env.CURRENT_COMMIT }}
      - name: Echo next version
        shell: bash
        run: |
          echo ${{ steps.get-next-version.outputs.next_version }}
  build-push-core-grpc-protos-nuget:
    needs: prepare-build
    name: Build .Net
    defaults:
      run:
        working-directory: src/csharp/Core.Grpc.Protos
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build & Push Nuget
        uses: ./.github/actions/build-push-net
        with:
          working_directory: "./src/csharp/Core.Grpc.Protos"
          github_token: ${{ secrets.PUSH_PACKAGE }}
          next_version: ${{ needs.prepare-build.outputs.next_version }}
  build-push-core-grpc-web-protos-npm:
    needs: prepare-build
    name: Build Npm
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build & Push Npm
        uses: ./.github/actions/build-push-npm
        with:
          working_directory: "./src/npm/core-grpc-web-protos"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          next_version: ${{ needs.prepare-build.outputs.next_version }}